name: Ghosty Tükör

on:
  schedule:
    # minden percben ellenőrzi az üzeneteket UTC-ben
    - cron: '*/1 * * * *'

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install gspread oauth2client requests
      - name: Run Ghosty Script
        run: |
          python3 send_ghosty.py
